version: '3'

services:
  hls_proxy_api:
    build:
      context: ./hls_proxy_api
    environment:
      - UDP_PORT_RANGE=20000-20004
      - PLAYER_BASE_URL
      - SERVER_BASE_URL
      - OUTPUT_PATH=/app/output
    ports:
      - "20000-20004:20000-20004/udp"
    depends_on:
      - hls_proxy_server
    volumes:
      - output:/app/output
  hls_proxy_server:
    build:
      context: ./hls_proxy_server
    environment:
      - PLAYER_BASE_URL
    ports:
      - 8080:80
    volumes:
      - output:/hls_output
  hls_proxy_player:
    build:
      context: ./hls_proxy_player
    environment:
      - SERVER_BASE_URL
    ports:
      - 8000:80
volumes:
  output:
